### PR TITLE
feat: POI and layer legend in sidebar

### PR DESCRIPTION
**Pull request by dnsos**
This PR adds the legend for POIs and layers to the sidebar.

Clicking the legend items doesn't do anything yet. I'm thinking about implementing that functionality once we merge this PR. What do you think, @vogelino & @lucasoeth?

### CODE REVIEW

**Review by lucasoeth — APPROVED** [review]
Wow good work @dnsos, it looks really good. I'd say we can merge it and implement the functionality on another branch. Maybe consider adding the warning logo if webp is not supported in this branch

**Comment by dnsos** [comment]
> Maybe consider adding the warning logo if webp is not supported in this branch

Good point, thanks for noticing. I will add it here.

**Review by vogelino — APPROVED** [review]
Amazing! Great adaptation for mobile too! Well done! Nothing to complain about :D

**Comment by dnsos** [comment]
Thank you for the reviews, @lucasoeth and @vogelino. I implemented the webp support note now as well.

**Pull request merged**
