### PR TITLE
feat(ERF-50): add map layers

### PR DESCRIPTION
**Pull request by dnsos**
This PR adds the necessary feature layers to the map:

- Mapbox Light style as a base map 
- shade layer (currently with only one example tileset for every hour)
- 3D buildings
- POIs (not interactive yet, exact colors TBD in ERF-79)

Screenshot 2021-06-16 at 20 02 36

### CODE REVIEW

**Review by vogelino — CHANGES_REQUESTED** [review]
### Looks amazing!
_I'm getting more and more excited about this project!_ **Well implemented too!** I have nothing to complain about on that side... **But**: I miss the tests and storybook stories though... 😅 Limited time shouldn't prevent you from adding at least some very basic tests 🥸  

I noticed also a few things:
1. The points are very crowded when zoomed out. Isn't there a way to display them smaller when zoomed out and/or reduce their white border size? (See screenshot below)
2. At a certain zoom level, the buildings lose their color (See the second screenshot). This looks like a bug. Any idea why? 

Screen Shot 2021-06-16 at 10 42 46 PM

Screen Shot 2021-06-16 at 10 42 54 PM

**Review by lucasoeth — APPROVED** [review]
Code looks great, the result looks even better.
I agree with @vogelino first comment.
Regarding his second comment, I think that is because when zoomed in the 3d building layer gets added and that overlays the wind/shade layer right? I think it looks good that way and we should keep the 3d buildings because it gives sense to the shadows.

Otherwise looks good to go. Thanks for taking on mapbox 💪

**Comment by dnsos** [comment]
> I think that is because when zoomed in the 3d building layer gets added and that overlays the wind/shade layer right?

Exactly. I changed the color of the buildings to a slightly darker grey shade now. Hopefully this solves the impression of being a bug, @vogelino?

Also, I improved the behaviour of the circle size when zoomed and added basic tests to the ma layers.

**Review by vogelino — APPROVED** [review]
Magnificient! Thank you for adding the tests! 👏 

> I changed the color of the buildings to a slightly darker grey shade now
I agree! It solves the problem!

**Pull request merged**
