### PR TITLE
ERF-63 disclaimer links

### PR DESCRIPTION
**Pull request by lucasoeth**
In this PR I am adding two links leading to Impressum and Datenschutz info

### CODE REVIEW

**Review by vogelino — APPROVED** [review]
Great initiative! Thx. My only comments would be:
1. There are no hover/focus styles
2. The links should have the attributes `target="_blank" rel="noreferrer"`
3. When the sidebar is opened, the links are kinda covered by it and it looks kinda broken

**Comment by lucasoeth** [comment]
> Great initiative! Thx. My only comments would be:
> 
>     1. There are no hover/focus styles
> 
>     2. The links should have the attributes `target="_blank" rel="noreferrer"`
> 
>     3. When the sidebar is opened, the links are kinda covered by it and it looks kinda broken

I implemented your comments, there is a hover effect, but it is very slight, and I didn't bother with focus since it redirects you anyways. I also added github link, what do you think @dnsos @vogelino

**Comment by vogelino** [comment]
Thx for the changes! Good adaptation to mobile! I still have a few comments:
- In my opinion, hover effects should be noticeable, which isn't the case.
- Also we need focus styles because these are there for keyboard navigation not for clicking (they are still relevant for clicking as they are visible when the user comes back on the page)
- The the links when the sidebar is opened are aligned to the end of the sidebar nav. I think it would look better if they were aligned to the left of the nav (see screenshot)

Screen Shot 2021-06-23 at 1 25 06 PM

**Review by vogelino — APPROVED** [review]
Great changes! Love it 👌

**Pull request merged**
