### PR TITLE
feat(AppTitle): Add AppTitle component

### PR DESCRIPTION
**Pull request by vogelino**
This PR adds the App title component to the /map route. When clicked, it leads to the / route and thus opens the splash screen

### CODE REVIEW

**Review by lucasoeth — CHANGES_REQUESTED** [review]
Code looks clean and the component looks good on screen aswell. Great addition. Only problem I found is that it overlaps with the map controls when on mobile. Maybe we shouldn't display it on mobile at all because there is not a lot of space to begin with? What do you think?

**Comment by vogelino** [comment]
> Code looks clean and the component looks good on screen as well. Great addition. Only problem I found is that it overlaps with the map controls when on mobile. Maybe we shouldn't display it on mobile at all because there is not a lot of space to begin with? What do you think?

True! I totally forgot the mobile styles! I didn't hide it on mobile because it is the only way to return to the splash screen but I made sure it doesn't overlap with the controls anymore. Merci!

**Review by dnsos — APPROVED** [review]
Nice job @vogelino.

This is exactly how I was thinking about the mobile version as well.

**Review by lucasoeth — APPROVED** [review]
Looks good on mobile now as well :)

**Pull request merged**
